-- 1. Crear tabla Personas
CREATE TABLE Personas (
    ID NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    TDoc VARCHAR2(5) CHECK (TDoc IN ('CC', 'CE', 'TI')) NOT NULL,
    NDoc VARCHAR2(20) NOT NULL UNIQUE,
    Nombres VARCHAR2(100) NOT NULL,
    Apellidos VARCHAR2(100) NOT NULL,
    Edad NUMBER(3) NOT NULL,
    Celular VARCHAR2(15) NOT NULL,
    Rol VARCHAR2(20) DEFAULT 'Usuario' CHECK (Rol IN ('Administrador', 'Usuario', 'Analista')) -- 
);

-- 2.consulta el rol 1
SELECT * FROM Personas WHERE Rol = 'Administrador';

-- se actualiza el rol 1 
UPDATE Personas SET Rol = 'Analista' WHERE ID = 1;
COMMIT;

-- lo mismo para elimianr el id numero 1 o el id 1 
DELETE FROM Personas WHERE ID = 1;
COMMIT;
